### ISSUE TITLE
fix video links and embed in header

### ISSUE THREAD

**Issue by mikelmaron** [mapkibera/map-kibera-schools#15]
the video isn’t actually on the header. it just says the words, video. you click, and nothing...

**Comment by mikelmaron** [comment]
this might be fixed in my un-committed changes

**Comment by bcarancibia** [comment]
@mikelmaron can you check to see if this is in the un-committed changes. This was working.

**Comment by mikelmaron** [comment]
@bcarancibia I don't think this was ever working actually

**Comment by uniphil** [comment]
It was implemented in [this commit](https://github.com/mapkibera/map-kibera-schools/commit/0913f479068d4797b7e9cfb0abc027735244ab28#diff-f2f8cfb1460d9cc55d1fcb90f53808caL26), and then [this commit](https://github.com/mapkibera/map-kibera-schools/commit/c18198229c33f24f9ba65b658dd916aa33930d80#diff-db4ff8f95a9381083b34203ca2882aafL18) broke it, and some others in smaller ways since I worked on that code.

in `videos.json`, to embed a youtube video, you have to define a `youtubeid` key on the object. It should be taken from the URL of the video, so for example this video:
https://www.youtube.com/watch?v=3yNSF7ljOoU
you could have
```json
[
  ...
  {
    "title": "Dear Kitten: Regarding The Dog",
    "description": "Cat and Kitten are back again blah blah blah...",
    "youtubeid": "3yNSF7ljOoU",
    "image": "img/some/image.jpg"
  },
  ...
]
```

That should work again, now.

**Comment by mikelmaron** [comment]
@uniphil, why does this require an image? can it be set up to just show the player?
